url: http://farseer.cn/ca2015
baseurl: /ca2015
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#markdown: rdiscount
permalink: /blog/:year:month:day/:title.html
highlighter: true
exclude: ['Rakefile.rb', 'CNAME', 'README.markdown']
